Added blog frontend and backend
himeshparashar/Social-Morph pull request #146
Opened 2024-10-21 17:51 UTC by Sourabh782

## 📋 Description

## 🔨 Changes Made

- Added blog frontend
- Added blog backend
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #37 

## How should this be tested?

- [ ] Test A
- [ ] Test B

## 📸 Screenshots (if applicable)

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-10-21 17:54 UTC, himeshparashar commented
@sudhanshutech  review needed

2024-10-22 05:52 UTC, sudhanshutech requested changes

2024-10-22 05:52 UTC, sudhanshutech commented on components/blog/Update_Card.tsx
> +                                        <button data-modal-target="authentication-modal" onClick={()=>createBlog()} className="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outlin
too much of re defining styles. Could be reused.

2024-10-22 05:52 UTC, sudhanshutech commented on lib/dbConnect.ts
> +import mongoose from "mongoose";
rename this root file from lib to config if you would .

2024-10-22 05:52 UTC, sudhanshutech commented on app/api/blog/route.ts
> +                message: "blog not found"
these could defined at one place as error handler middleware so you don't have redefine everywhere.

2024-10-22 05:52 UTC, sudhanshutech commented on components/blog/BlogCard.tsx
> +        console.log(res)
remove console logs when testing is done because we don't want to display users responses in console.

2024-10-22 05:52 UTC, sudhanshutech commented on components/blog/Update_Card.tsx
> +        const response = await fetch("/api/blog", {
cors is taken care right?

2024-10-22 05:54 UTC, sudhanshutech commented
@Sourabh782 please if you would provide some recording of your work.

2024-10-22 06:08 UTC, Sourabh782 commented
> @Sourabh782 please if you would provide some recording of your work.

Yess sure

2024-10-22 06:43 UTC, Sourabh782 commented on lib/dbConnect.ts
> +import mongoose from "mongoose";
like this? 
![image](https://github.com/user-attachments/assets/d18cbbb8-66d5-4024-9491-0ab085a9869b)

2024-10-22 06:44 UTC, Sourabh782 commented on components/blog/BlogCard.tsx
> +        console.log(res)
removed

2024-10-22 13:37 UTC, sudhanshutech commented
@Sourabh782 how does this blogs look like to non authorized users?

2024-10-22 13:54 UTC, Sourabh782 commented
> @Sourabh782 how does this blogs look like to non authorized users?

@sudhanshutech  if user are not logged in they will not be able to see update or delete option its only for owner, i have used conditional rendering for it
![image](https://github.com/user-attachments/assets/4226958e-2cfe-4f91-ba61-449f47fbda4b)

2024-10-23 03:24 UTC, Sourabh782 commented
> @Sourabh782 how does this blogs look like to non authorized users?

Also if user is not logged in so he wont see Add button on top at blog page
![image](https://github.com/user-attachments/assets/111630ac-d181-4ce1-b3b8-b904e96cca55)

2024-10-24 03:03 UTC, Sourabh782 commented
@sudhanshutech , @himeshparashar can you check now? implemented some changes
1. removed console.log() statements
2. conditional rendering for users not logged in

2024-10-24 16:13 UTC, merged