made dashboard responsive
himeshparashar/Social-Morph pull request #149
Opened 2024-10-21 23:46 UTC by swatified

Hey I made dashboard responsive as reviewed by @Shobhit-Nagpal and @sudhanshutech 

https://github.com/user-attachments/assets/a37dd550-42b0-4b64-85c8-cbfd183dcfba

You can update the earlier level or assign this level1 if you dont mind.

2024-10-21 23:47 UTC, swatified commented
@himeshparashar have a look. this is under #86

2024-10-22 05:37 UTC, sudhanshutech requested changes

2024-10-22 05:37 UTC, sudhanshutech commented on app/dashboard/page.tsx
> +        console.log("Generating content with prompt:", fullPrompt);
remove the console logs please

2024-10-22 05:37 UTC, sudhanshutech commented
looks good to me . good work @swatified

2024-10-22 18:37 UTC, merged

2024-10-22 19:03 UTC, swatified commented
@himeshparashar please check once :(

My two issues got merged in single pr somehow. i didnt even raise for gemini text generation yet. but level 2?? for dashboard responsive.. then what about my gemini one? consider once :') cz it cant be recommited now na. only levels can be changed. either increase here or give here for gemini and dashboard responsive one's can go int dashboard ui fix i made? can update level there or sum? @himeshparashar hope im making sense

2024-10-22 19:05 UTC, swatified commented
i mean issue #54 and #86 got merged in this pr sadly :') @himeshparashar

2024-10-22 20:01 UTC, himeshparashar commented
@swatified please use branching to avoid this type of situation create a new branch for every new issue 

for now I have changed the title considering for both responsive and gemini generation 

and will add level 2 for now 

and for the gemini generation I have suggested a popup modal if you wish to work on that 
then that will make a another new pr I will add level 1 or 2 accordingly 

does this solves this ? (actually very confusion to me also 🥲)

2024-10-23 11:11 UTC, swatified commented
I asked for more levels because of two owkrs getting mixed actually? 😔 but it got down to from 2 to 1 now lol. Yes I'm working on that way rn. Sorry for creating chaos. I apologize.

2024-10-24 16:05 UTC, himeshparashar commented
@swatified will give you lvl 3 on the other pr for the popup part

2024-10-24 16:11 UTC, swatified commented
@himeshparashar okie but am doing it as redirection to other page tho. not pop-up way

2024-10-24 16:20 UTC, himeshparashar commented
@swatified ok