Add AI-Powered Hashtag Suggestions for Social Media Posts
himeshparashar/Social-Morph pull request #177
Opened 2024-10-29 15:07 UTC by sezallagwal

## 📋 Description

## 🔨 Changes Made

- Enhance Social Morph's capabilities by integrating an AI-powered hashtag suggestion feature. 
- Implement an AI-based algorithm to analyze the content of the post.
- Provide a list of relevant hashtags based on current trends and keywords.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #124

## How should this be tested?

- [x] Test A: use topic: "sezal"
- [x] Test B: use topic: "sezal lagwal"

## 📸 Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/a5610194-45b0-486d-8aca-782043426a1a)

![image](https://github.com/user-attachments/assets/8f135768-65bc-4592-9ac5-53c6129387a1)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-10-29 15:16 UTC, sezallagwal commented
@himeshparashar can you add level 3?

2024-10-30 04:48 UTC, sudhanshutech requested changes

2024-10-30 04:48 UTC, sudhanshutech commented on app/(root)/dashboard/page.tsx
> +console.log(apiKey);
remove the console please and specially don't console a api key😅

2024-10-30 04:48 UTC, sudhanshutech commented on app/(root)/dashboard/page.tsx
> +          "Gemini API key is not set. Please check your environment variables."
User can not check a environment variable, instead you can say: Please contact project owner or support

2024-10-30 04:48 UTC, sudhanshutech commented on app/(root)/dashboard/page.tsx
> +      console.log("Generating content with prompt:", fullPrompt);
remove please

2024-10-30 04:48 UTC, sudhanshutech commented on app/(root)/dashboard/page.tsx
> +      console.log("Processing response...");
remove all consoles when you have done testing

2024-10-31 06:02 UTC, sezallagwal commented
@sudhanshutech is it okay now?

2024-11-03 16:55 UTC, merged